#!/usr/bin/env bash

sudo \
  LOCAL_SOURCE_PATH="$LOCAL_SOURCE_PATH" \
  COMPILER_VERSION="$COMPILER_VERSION" \
  CHROME_RUNNER_VERSION="$CHROME_RUNNER_VERSION" \
  FIREFOX_RUNNER_VERSION="$FIREFOX_RUNNER_VERSION" \
  DELEGATOR_VERSION="$DELEGATOR_VERSION" \
  WORKER_VERSION="$WORKER_VERSION" \
  docker compose down --remove-orphans

sleep 10
