#!/usr/bin/env bash

echo "COMPILER_VERSION=$COMPILER_VERSION"
echo "CHROME_RUNNER_VERSION=$CHROME_RUNNER_VERSION"
echo "FIREFOX_RUNNER_VERSION=$FIREFOX_RUNNER_VERSION"
echo "DELEGATOR_VERSION=$DELEGATOR_VERSION"
echo "WORKER_VERSION=$WORKER_VERSION"
