name: Debug - Dump Github Context

on:
  push:
    branches:
      - main
  pull_request:
  release:

jobs:
  main:
    name: Dump Github Context
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Examine current branch
        run: git branch

      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
