name: Debug worker-release event

on:
  repository_dispatch:
    types: [worker-release]

jobs:
  build:
    name: Test Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Examine current branch
        run: git branch

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump client payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD"

      - name: Dump versions
        env:
          COMPILER_VERSION: ${{ github.event.client_payload.compiler_version }}
          CHROME_RUNNER_VERSION: ${{ github.event.client_payload.chrome_runner_version }}
          FIREFOX_RUNNER_VERSION: ${{ github.event.client_payload.firefox_runner_version }}
          DELEGATOR_VERSION: ${{ github.event.client_payload.delegator_version }}
          WORKER_VERSION: ${{ github.event.client_payload.worker_version }}
        run:
          echo "compiler_version" $COMPILER_VERSION
          echo "chrome_runner_version" $CHROME_RUNNER_VERSION
          echo "firefox_runner_version" $FIREFOX_RUNNER_VERSION
          echo "delegator_version" $DELEGATOR_VERSION
          echo "worker_version" $WORKER_VERSION
