name: Debug published release

on:
  release:
    types:
      - published
jobs:
  build:
    name: Debug published release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Examine current branch
        run: git branch

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
