name: "[Temp] Investigate release payload"

on:
  release:
    types:
      - published

jobs:
  build:
    name: Investigate release payload Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "$CONTEXT"

      - name: Dump release tag name
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo $RELEASE_TAG_NAME

      - name: Dump assets context
        env:
          CONTEXT: ${{ toJson(github.event.release.assets) }}
        run: echo "$CONTEXT"

      - name: Build image versions url
        id: image-versions-url
        env:
          URL_TEMPLATE: https://github.com/smartassert/worker-deploy/releases/download/{{ version }}/image-versions.env
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          URL=$(echo $URL_TEMPLATE | sed "s@{{ version }}@$RELEASE_TAG_NAME@g")
          echo "::set-output name=value::$URL"

      - name: Get image versions
        env:
          IMAGE_VERSIONS_URL: ${{ steps.image-versions-url.outputs.value }}
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $IMAGE_VERSIONS_URL)

          if [ "200" == "STATUS_CODE" ]; then
            echo "exists"
          else
            echo "not exists"
          fi

#          echo IMAGE_VERSIONS_URL $IMAGE_VERSIONS_URLL
#          IMAGE_VERSIONS=$(curl -L $IMAGE_VERSIONS_URL)
#          echo $IMAGE_VERSIONS
#          echo $IMAGE_VERSIONS > .image-versions.env

      - name: Dump image versions
        run: |
          ls -la
          cat .image-versions.env
          while read line
          do
            key=$(echo $line | cut -d'=' -f1)
            value=$(echo $line | cut -d'=' -f2)
            echo "::set-output name=$key::$value"
          done < .image-versions.env
