name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.value }}
      snapshot-name: ${{ steps.snapshot-name.outputs.value }}
      compiler-version: ${{ steps.image-versions.outputs.COMPILER_VERSION }}
      chrome-runner-version: ${{ steps.image-versions.outputs.CHROME_RUNNER_VERSION }}
      firefox-runner-version: ${{ steps.image-versions.outputs.FIREFOX_RUNNER_VERSION }}
      delegator-version: ${{ steps.image-versions.outputs.DELEGATOR_VERSION }}
      worker-version: ${{ steps.image-versions.outputs.WORKER_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        id: version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Output version
        run: echo ${{ steps.version.outputs.value }}

      - name: Set snapshot name
        id: snapshot-name
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
          VERSION: ${{ steps.version.outputs.value }}
        run: echo "::set-output name=value::$(./ci/create-snapshot-name.sh)"

      - name: Output snapshot name
        run: echo ${{ steps.snapshot-name.outputs.value }}

      - name: Get versions from image-versions.env
        id: image-versions
        env:
          ENV_FILE_PATH: ./image-versions.env
        run: ./ci/read-env-file.sh

      - name: Output image versions
        env:
          COMPILER_VERSION: ${{ steps.image-versions.outputs.COMPILER_VERSION }}
          CHROME_RUNNER_VERSION: ${{ steps.image-versions.outputs.CHROME_RUNNER_VERSION }}
          FIREFOX_RUNNER_VERSION: ${{ steps.image-versions.outputs.FIREFOX_RUNNER_VERSION }}
          DELEGATOR_VERSION: ${{ steps.image-versions.outputs.DELEGATOR_VERSION }}
          WORKER_VERSION: ${{ steps.image-versions.outputs.WORKER_VERSION }}
        run: |
          echo COMPILER_VERSION $COMPILER_VERSION
          echo CHROME_RUNNER_VERSION $CHROME_RUNNER_VERSION
          echo FIREFOX_RUNNER_VERSION $FIREFOX_RUNNER_VERSION
          echo DELEGATOR_VERSION $DELEGATOR_VERSION
          echo WORKER_VERSION $WORKER_VERSION

  release:
    needs: setup
    name: Release
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      VERSION: ${{ needs.setup.outputs.version }}
      SNAPSHOT_NAME: ${{ needs.setup.outputs.snapshot-name }}
      COMPILER_VERSION: ${{ needs.setup.outputs.compiler-version }}
      CHROME_RUNNER_VERSION: ${{ needs.setup.outputs.chrome-runner-version }}
      FIREFOX_RUNNER_VERSION: ${{ needs.setup.outputs.firefox-runner-version }}
      DELEGATOR_VERSION: ${{ needs.setup.outputs.delegator-version }}
      WORKER_VERSION: ${{ needs.setup.outputs.worker-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          packer --version

      - name: Verify image configuration
        run: packer validate image.pkr.hcl
#
#      - name: Create snapshot
#        id: snapshot
#        run: |
#          packer build image.pkr.hcl | tee packer.log
#          ID=$(cat packer.log | tail -1 | grep -P -o 'ID: \d+' | tr -d 'ID: ')
#          echo "::set-output name=id::$ID"
#
#      - name: Verify snapshot exists
#          ID: ${{ steps.snapshot.outputs.id }}
#        run: ./ci/verify-snapshot-exists.sh
#
#      - name: Remove snapshot if not a release
#        if: ${{ github.event_name != 'release' }}
#          ID: ${{ steps.snapshot.outputs.id }}
#        run: |
#          ./ci/delete-snapshot.sh
#          ./ci/verify-snapshot-not-exists.sh
#
#      - name: Trigger deploy workflow if this a release
#        if: ${{ github.event_name == 'release' }}
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: Deploy
#          token: ${{ secrets.PAT_TOKEN_SELF }}
#          inputs: |
#            {
#              "image_id": "${{ steps.snapshot.outputs.id }}"
#            }
