name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      should-deploy:
        description: Deploy after building image?
        required: true
        default: "false"
      version:
        description: Existing version to release
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.should-deploy.outputs.value }}
      version: ${{ steps.version.outputs.value }}
      snapshot-name: ${{ steps.snapshot-name.outputs.value }}
      compiler-version: ${{ steps.image-versions.outputs.COMPILER_VERSION }}
      chrome-runner-version: ${{ steps.image-versions.outputs.CHROME_RUNNER_VERSION }}
      firefox-runner-version: ${{ steps.image-versions.outputs.FIREFOX_RUNNER_VERSION }}
      delegator-version: ${{ steps.image-versions.outputs.DELEGATOR_VERSION }}
      worker-version: ${{ steps.image-versions.outputs.WORKER_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Use specific version?
        id: use-specific-version
        env:
          VALUE: ${{ github.event.inputs.version }}
        run: echo "::set-output name=value::$(./scripts/is-value-set.sh)"

      - name: Output use specific version
        run: echo ${{ steps.use-specific-version.outputs.value }}

      - name: Set version
        id: version
        env:
          VALUE1: ${{ github.event.inputs.version }}
          VALUE2: ${{ github.event.release.tag_name }}
          DEFAULT: master
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/select-defined-variable-or-default.sh)"

      - name: Output version
        env:
          VALUE: ${{ steps.version.outputs.value }}
        run: |
          [ "" != "$VALUE" ] && echo "$VALUE"

      - name: Get image versions for specified version?
        if: ${{ steps.use-specific-version.outputs.value == 'true' }}
        env:
          REPO: ${{ github.repository }}
          VERSION: ${{ steps.version.outputs.value }}
          FILE_PATH: ./image-versions.env
        run: ./vendor/smartassert/bash-ga-ci-tools/src/get-gh-file.sh.sh

      - name: Deploy after building image?
        id: should-deploy
        env:
          EXPECTED: release
          ACTUAL: ${{ github.event_name }}
          DEFAULT: ${{ github.event.inputs.should-deploy }}
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/boolean-if-actual-is-expected-else-default.sh)"

      - name: Output should deploy
        run: echo ${{ steps.should-deploy.outputs.value }}

      - name: Set snapshot name
        id: snapshot-name
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
          VERSION: ${{ steps.version.outputs.value }}
        run: |
          SNAPSHOT_NAME=$(./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/create-name.sh)
          echo "::set-output name=value::$SNAPSHOT_NAME"

      - name: Output snapshot name
        env:
          VALUE: ${{ steps.snapshot-name.outputs.value }}
        run: |
          [ "" != "$VALUE" ] && echo "$VALUE"

      - name: Checkout bash-read-env-file
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-read-env-file
          path: ./vendor/smartassert/bash-read-env-file
          ref: main

      - name: Read image versions
        id: image-versions
        env:
          ENV_FILE_PATH: ./image-versions.env
        run: ./vendor/smartassert/bash-read-env-file/src/read-env-file-ga.sh

      - name: Output image versions
        env:
          COMPILER_VERSION: ${{ steps.image-versions.outputs.COMPILER_VERSION }}
          CHROME_RUNNER_VERSION: ${{ steps.image-versions.outputs.CHROME_RUNNER_VERSION }}
          FIREFOX_RUNNER_VERSION: ${{ steps.image-versions.outputs.FIREFOX_RUNNER_VERSION }}
          DELEGATOR_VERSION: ${{ steps.image-versions.outputs.DELEGATOR_VERSION }}
          WORKER_VERSION: ${{ steps.image-versions.outputs.WORKER_VERSION }}
        run: ./scripts/create-release-notes.sh

  create-image:
    needs: setup
    name: Create image
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      VERSION: ${{ needs.setup.outputs.version }}
      SNAPSHOT_NAME: ${{ needs.setup.outputs.snapshot-name }}
      COMPILER_VERSION: ${{ needs.setup.outputs.compiler-version }}
      CHROME_RUNNER_VERSION: ${{ needs.setup.outputs.chrome-runner-version }}
      FIREFOX_RUNNER_VERSION: ${{ needs.setup.outputs.firefox-runner-version }}
      DELEGATOR_VERSION: ${{ needs.setup.outputs.delegator-version }}
      WORKER_VERSION: ${{ needs.setup.outputs.worker-version }}
    outputs:
      image-id: ${{ steps.image.outputs.id }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Validate image configuration
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: image.pkr.hcl

      - name: Set packer log path
        id: packer-log-path
        run: echo "::set-output name=value::./packer.log"

      - name: Create image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-machine-readable"
          target: image.pkr.hcl
        env:
          PACKER_LOG: 1
          PACKER_LOG_PATH: ${{ steps.packer-log-path.outputs.value }}

      - name: Extract image ID from packer log
        id: image
        env:
          PACKER_LOG_PATH: ${{ steps.packer-log-path.outputs.value }}
        run: echo "::set-output name=id::$(./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/extract-id-from-packer-log.sh)"

      - name: Verify image exists
        env:
          IMAGE_ID: ${{ steps.image.outputs.id }}
          EXPECTED_EXISTS: "true"
        run: ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh

  trigger-deploy:
    needs: [setup, create-image]
    name: Trigger deploy workflow
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.should-deploy == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.PAT_TOKEN_SELF }}
          inputs: |
            {
              "image_id": "${{ needs.create-image.outputs.image-id }}"
            }

  remove-snapshot:
    needs: create-image
    name: Remove snapshot if not deploying
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.should-deploy == 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Remove snapshot
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          IMAGE_ID: ${{ needs.create-image.outputs.image-id }}
          EXPECTED_EXISTS: "false"
        run: |
          ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/delete.sh
          ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh
