name: Release

on:
  push:
#    branches:
#      - master
  pull_request:
#    branches:
#      - master
#  release:
#    types:
#      - published
#  repository_dispatch:
#    types: [worker-release]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        id: version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          WORKER_VERSION: ${{ github.event.client_payload.worker_version }}
        run: |
          VERSION_LABEL=$(./ci/create-version-label.sh)
          echo "::set-output name=value::$VERSION_LABEL"
