name: Build Image

on:
  push:
#    branches:
#      - master
  pull_request:
#    branches:
#      - master
#  release:
#    types:
#      - published
#  repository_dispatch:
#    types: [worker-release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
