name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      should-deploy:
        description: Deploy after building image?
        required: true
        default: "false"
      version:
        description: Existing version to release
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ env.SHOULD_DEPLOY }}
      version: ${{ env.VERSION }}
      snapshot-name: ${{ env.SNAPSHOT_NAME }}
      compiler-version: ${{ env.COMPILER_VERSION }}
      chrome-runner-version: ${{ env.CHROME_RUNNER_VERSION }}
      firefox-runner-version: ${{ env.FIREFOX_RUNNER_VERSION }}
      delegator-version: ${{ env.DELEGATOR_VERSION }}
      worker-version: ${{ env.WORKER_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v6
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v6
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Use specific version?
        env:
          VALUE: ${{ github.event.inputs.version }}
        run: echo "USE_SPECIFIC_VERSION=$(./vendor/smartassert/bash-ga-ci-tools/src/is-value-set.sh)" >> "$GITHUB_ENV"

      - name: Set version
        env:
          VALUE1: ${{ github.event.inputs.version }}
          VALUE2: ${{ github.event.release.tag_name }}
          DEFAULT: master
        run: echo "VERSION=$(./vendor/smartassert/bash-ga-ci-tools/src/select-defined-variable-or-default.sh)" >> "$GITHUB_ENV"

      - name: Get image versions for specified version?
        if: ${{ env.USE_SPECIFIC_VERSION == 'true' }}
        env:
          REPO: ${{ github.repository }}
          VERSION: ${{ env.VERSION }}
          FILE_PATH: ./image-versions.env
        run: ./vendor/smartassert/bash-ga-ci-tools/src/get-gh-file.sh

      - name: Deploy after building image?
        env:
          EXPECTED: release
          ACTUAL: ${{ github.event_name }}
          DEFAULT: ${{ github.event.inputs.should-deploy }}
        run: echo "SHOULD_DEPLOY=$(./vendor/smartassert/bash-ga-ci-tools/src/boolean-if-actual-is-expected-else-default.sh)" >> "$GITHUB_ENV"

      - name: Set snapshot name
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
          VERSION: ${{ env.VERSION }}
        run: |
          SNAPSHOT_NAME=$(./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/create-name.sh)
          echo "SNAPSHOT_NAME=$SNAPSHOT_NAME" >> "$GITHUB_ENV"

      - name: Read image versions
        env:
          ENV_FILE_PATH: ./image-versions.env
        run: sed '/^$/d' "$ENV_FILE_PATH" >> "$GITHUB_ENV"

  verify-setup:
    name: Verify setup
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v6
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Output
        env:
          OUTPUTS: ${{ toJson(needs.setup.outputs) }}
        run: |
          echo "$OUTPUTS"
          ./vendor/smartassert/bash-ga-ci-tools/src/json-contains-no-empty-values.sh


  create-image:
    needs: [setup, verify-setup]
    name: Create image
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      VERSION: ${{ needs.setup.outputs.version }}
      SNAPSHOT_NAME: ${{ needs.setup.outputs.snapshot-name }}
      COMPILER_VERSION: ${{ needs.setup.outputs.compiler-version }}
      CHROME_RUNNER_VERSION: ${{ needs.setup.outputs.chrome-runner-version }}
      FIREFOX_RUNNER_VERSION: ${{ needs.setup.outputs.firefox-runner-version }}
      DELEGATOR_VERSION: ${{ needs.setup.outputs.delegator-version }}
      WORKER_VERSION: ${{ needs.setup.outputs.worker-version }}
    outputs:
      image-id: ${{ env.IMAGE_ID }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v6

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v6
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Validate image configuration
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: image.pkr.hcl

      - name: Set packer log path
        run: echo "PACKER_LOG_PATH=./packer.log" >> "$GITHUB_ENV"

      - name: Create image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-machine-readable"
          target: image.pkr.hcl
        env:
          PACKER_LOG: 1
          PACKER_LOG_PATH: ${{ env.PACKER_LOG_PATH }}

      - name: Extract image ID from packer log
        env:
          PACKER_LOG_PATH: ${{ env.PACKER_LOG_PATH }}
        run: echo "IMAGE_ID=$(./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/extract-id-from-packer-log.sh)" >> "$GITHUB_ENV"

      - name: Verify image exists
        env:
          IMAGE_ID: ${{ env.IMAGE_ID }}
          EXPECTED_EXISTS: "true"
        run: ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh

  trigger-deploy:
    needs: [setup, create-image]
    name: Trigger deploy workflow
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.should-deploy == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger deploy workflow
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
          IMAGE_ID: ${{ needs.create-image.outputs.image-id }}
        run: gh workflow run deploy.yml -f image_id="$IMAGE_ID"

  remove-snapshot:
    needs: [setup, create-image]
    name: Remove snapshot if not deploying
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.should-deploy == 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v6
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Remove snapshot
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          IMAGE_ID: ${{ needs.create-image.outputs.image-id }}
          EXPECTED_EXISTS: "false"
        run: |
          ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/delete.sh
          ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh
