name: Repository Dispatch Listener

on:
  repository_dispatch:
    types: [worker-release]

jobs:
  build:
    name: Test Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump client payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD"

      - name: Dump versions
        env:
          PAYLOAD: ${{ github.event.client_payload }}
        run:
          echo "compiler_version" $PAYLOAD.compiler_version
          echo "chrome_runner_version" $PAYLOAD.chrome_runner_version
          echo "firefox_runner_version" $PAYLOAD.firefox_runner_version
          echo "delegator_version" $PAYLOAD.delegator_version
          echo "worker_version" $PAYLOAD.worker_version
