name: Store image versions

on:
  repository_dispatch:
    types: [worker-release]

jobs:
  build:
    name: Store image versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Output payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD"

      - name: Update image-versions.env
        if: ${{ github.event.client_payload.worker_version != 'master' }}
        env:
          COMPILER_VERSION: ${{ github.event.client_payload.compiler_version }}
          CHROME_RUNNER_VERSION: ${{ github.event.client_payload.chrome_runner_version }}
          FIREFOX_RUNNER_VERSION: ${{ github.event.client_payload.firefox_runner_version }}
          DELEGATOR_VERSION: ${{ github.event.client_payload.delegator_version }}
          WORKER_VERSION: ${{ github.event.client_payload.worker_version }}
        run: ./scripts/create-image-versions-env.sh > image-versions.env

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic image-versions.env for worker release ${{ github.event.client_payload.worker_version }}"

      - name: Get latest commit hash
        id: commit-hash
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        run: echo "::set-output name=value::$(git rev-parse HEAD)"

      - name: Trigger create-release workflow
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Create release
          token: ${{ secrets.PAT_TOKEN_SELF }}
          inputs: |
            {
              "commit-hash": "${{ steps.commit-hash.outputs.value }}",
              "should-release": "${{ steps.commit-hash.outputs.value }}"
            }
