name: Store image versions

on:
  repository_dispatch:
    types: [worker-release]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      worker-version: ${{ github.event.client_payload.worker_version }}
      compiler-version: ${{ github.event.client_payload.compiler_version }}
      chrome-runner-version: ${{ github.event.client_payload.chrome_runner_version }}
      firefox-runner-version: ${{ github.event.client_payload.firefox_runner_version }}
      delegator-version: ${{ github.event.client_payload.delegator_version }}

    steps:
      - name: Output payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD"

  verify-setup:
    name: Verify setup
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Output
        env:
          OUTPUTS: ${{ toJson(needs.setup.outputs) }}
        run: echo "$OUTPUTS"

  store:
    name: Store
    runs-on: ubuntu-latest
    needs: [setup, verify-setup]
    if: ${{ needs.setup.outputs.worker-version != 'master' }}
    outputs:
      create-release: ${{ steps.auto-commit-action.outputs.changes_detected }}
      commit-hash: ${{ steps.auto-commit-action.outputs.commit_hash }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Update
        env:
          COMPILER_VERSION: ${{ needs.setup.outputs.compiler-version }}
          CHROME_RUNNER_VERSION: ${{ needs.setup.outputs.chrome-runner-version }}
          FIREFOX_RUNNER_VERSION: ${{ needs.setup.outputs.firefox-runner-version }}
          DELEGATOR_VERSION: ${{ needs.setup.outputs.delegator-version }}
          WORKER_VERSION: ${{ needs.setup.outputs.worker-version }}
        run: ./scripts/create-image-versions-env.sh > image-versions.env

      - name: Commit
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic image-versions.env for worker release ${{ needs.setup.outputs.worker-version }}"

  trigger-create-release:
    name: Trigger create release workflow
    runs-on: ubuntu-latest
    needs: [setup, store]
    if: ${{ needs.store.outputs.create-release == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Trigger create-release workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Create release
          token: ${{ secrets.PAT_TOKEN_SELF }}
          inputs: |
            {
              "commit-hash": "${{ needs.store.outputs.commit-hash }}",
              "should-release": "true"
            }
