name: VirtualBox VM

on:
#  push:
#    branches:
#      - master
  pull_request:
#    branches:
#      - master

jobs:
  build:
    name: Build
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show package versions
        run: |
          vagrant --version
          VBoxManage --version

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/focal-server-cloudimg-amd64-vagrant
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Validate Vagrantfile
        run: vagrant validate

      - name: Lint provision.sh
        run: |
          brew install shellcheck
          shellcheck provision.sh
          shellcheck self-test/*.sh

      - name: Get versions from .image-versions.env
        id: dependency-versions
        run: |
          while read line
          do
            key=$(echo $line | cut -d'=' -f1)
            value=$(echo $line | cut -d'=' -f2)
            echo "::set-output name=$key::$value"
          done <<<$(cat .image-versions.env)

      - name: Examine versions
        run: |
          echo steps.dependency-versions.outputs.COMPILER_VERSION ${{ steps.dependency-versions.outputs.COMPILER_VERSION }}
          echo steps.dependency-versions.outputs.CHROME_RUNNER_VERSION ${{ steps.dependency-versions.outputs.CHROME_RUNNER_VERSION }}
          echo steps.dependency-versions.outputs.FIREFOX_RUNNER_VERSION ${{ steps.dependency-versions.outputs.FIREFOX_RUNNER_VERSION }}
          echo steps.dependency-versions.outputs.DELEGATOR_VERSION ${{ steps.dependency-versions.outputs.DELEGATOR_VERSION }}
          echo steps.dependency-versions.outputs.WORKER_VERSION ${{ steps.dependency-versions.outputs.WORKER_VERSION }}

      - name: Vagrant up
        run: |
          COMPILER_VERSION=0.29 \
          CHROME_RUNNER_VERSION=0.18 \
          FIREFOX_RUNNER_VERSION=0.18 \
          DELEGATOR_VERSION=0.6 \
          WORKER_VERSION=0.4 \
          HOST_PORT=80 \
          vagrant up basil_worker
